version: "3"

services:
  server:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - database
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tournament-manager
      MYSQL_USER: examjava
      MYSQL_PASSWORD: examjavapassword
    ports:
      - "3306:3306"

volumes:
  data:
